import os
import json
import subprocess
import sys
from dotenv import load_dotenv

# Load API keys
base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(base_dir, ".env"))

try:
    from swarms import Agent, Swarm, SequentialWorkflow
except ImportError:
    print("⚠️ Swarms library not found. Please run 'pip install swarms'")
    sys.exit(1)

# Configuration from environment
HERMES_MODEL = os.getenv("HERMES_MODEL", "gpt-4o-mini")
HERMES_PROVIDER = os.getenv("HERMES_PROVIDER", "openai")
HERMES_API_KEY = os.getenv("HERMES_API_KEY")

# --- Tools ---
def run_audit(url: str):
    """Run the SEO audit script for a given URL"""
    result = subprocess.run([sys.executable, "scripts/analyze_site.py", url], capture_output=True, text=True)
    return result.stdout

def run_fix(action_id: str, title: str, repo: str):
    """Run the SEO fix script for a specific task"""
    result = subprocess.run([sys.executable, "scripts/apply_fix.py", action_id, title, repo], capture_output=True, text=True)
    return result.stdout

def run_social_publish():
    """Run the social media publishing script"""
    result = subprocess.run([sys.executable, "scripts/publish_socials.py"], capture_output=True, text=True)
    return result.stdout

# Define Agent Personas
def create_seo_auditor():
    return Agent(
        agent_name="SEO Auditor",
        system_prompt="""You are the lead SEO Auditor, the 'Eyes' of the swarm.
        
        BEHAVIOR & ETHOS:
        - Be ultra-meticulous. Scan for every possible technical gap.
        - Prioritize high-impact fixes (Titles, Meta, H-tags, Alt-text).
        - Maintain data integrity; ensure 'data/strategy.json' is actionable.
        
        TASKS:
        1. Receive the target URL.
        2. Use the 'run_audit' tool to scrape and analyze the site.
        3. Verify that 'runtime/outputs/actions.json' contains at least 3 high-value tasks.
        4. Pass the findings to the Engineer.""",
        model_name=HERMES_MODEL,
        tools=[run_audit],
        max_loops=1,
        autosave=True,
        dashboard=False
    )

def create_seo_engineer():
    return Agent(
        agent_name="SEO Engineer",
        system_prompt="""You are the lead SEO Software Engineer, the 'Hands' of the swarm.
        
        BEHAVIOR & ETHOS:
        - Be careful with code. Use isolated branches for every fix.
        - Ensure all changes follow the 'before_code' / 'after_code' pattern strictly.
        - Communicate clearly in commit messages and PR descriptions.
        
        TASKS:
        1. Read 'runtime/outputs/actions.json' generated by the Auditor.
        2. For each task in PENDING status:
           - Call 'run_fix' with the correct action_id and title.
           - Ensure the GitHub Repo URL is correctly passed.
        3. Confirm that Pull Requests are successfully created.
        4. Report implementation success to the Marketer.""",
        model_name=HERMES_MODEL,
        tools=[run_fix],
        max_loops=1,
        autosave=True,
        dashboard=False
    )

def create_social_marketer():
    return Agent(
        agent_name="Social Marketer",
        system_prompt="""You are the Growth Marketer, the 'Voice' of the swarm.
        
        BEHAVIOR & ETHOS:
        - Be creative and engaging. Use a 'Build in Public' tone.
        - Highlight the specific technical wins achieved by the Engineer.
        - Ensure all social signals (X, Mastodon) are published successfully.
        
        TASKS:
        1. Wait for the Engineer to confirm code fixes.
        2. Use the 'run_social_publish' tool to broadcast the updates.
        3. Verify that at least one platform (X or Mastodon) has successfully posted.
        4. Summarize the swarm's achievements for the final report.""",
        model_name=HERMES_MODEL,
        tools=[run_social_publish],
        max_loops=1,
        autosave=True,
        dashboard=False
    )

def run_swarm_automation():
    target_url = os.getenv("TARGET_URL", "https://thespecialcharacter.com/")
    repo_url = os.getenv("GITHUB_REPO", "https://github.com/tirthpatel143/The-Special-Character.git")

    print(f"🚀 Initializing SEO Command Center Swarm for: {target_url}")
    
    # Initialize agents
    auditor = create_seo_auditor()
    engineer = create_seo_engineer()
    marketer = create_social_marketer()

    # Define Workflow
    workflow = SequentialWorkflow(
        name="SEO-Optimization-Swarm",
        agents=[auditor, engineer, marketer],
        max_loops=1
    )

    # Execute Workflow
    task_description = f"""
    1. AUDIT: Run 'scripts/analyze_site.py' for {target_url}.
    2. ENGINEER: Read 'runtime/outputs/actions.json' and for each task, run 'scripts/apply_fix.py' targeting {repo_url}.
    3. MARKET: Run 'scripts/publish_socials.py' to announce the updates.
    """
    
    print("🤖 Swarm is starting the autonomous loop...")
    workflow.run(task_description)
    print("✅ SEO Swarm Automation Complete!")

if __name__ == "__main__":
    run_swarm_automation()
